import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import AddButton from "../components/AddButton";
import CerEditor from "../components/CerEditor";
import Operations from "../components/Operations";
import Stack from "../components/Stack";

const SContainer = styled.div`
  width: 100%;
  min-height: 100vh;
  display: flex;
  justify-content: space-around;
  align-items: center;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SContainer>
        <CerEditor />
        <AddButton />
        <Stack />
        <Operations />
      </SContainer>
    </div>
  );
};

export default Home;
